version: "3.2"
services:
  db:
    image: postgres
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
  web:
    build: .
    image: app
    command: ./scripts/start.sh
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        source: bundle
        target: /bundle
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - TS_CRM_DATABASE_HOST=db
      - TS_CRM_DATABASE_USER=postgres
  test:
    build: .
    image: app
    command: ./scripts/test.sh
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        source: bundle
        target: /bundle
    links:
      - db
    depends_on:
      - db
    environment:
      - RAILS_ENV=test
      - DB=postgres
      - TS_CRM_DATABASE_HOST=db
      - TS_CRM_DATABASE_USER=postgres
  artifact:
    build:
      context: .
      args:
        BUNDLE_INSTALL_OPTS: --without development test --deployment --path /bundle
    image: app
    command: ./scripts/build.sh
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        source: bundle
        target: /bundle
    environment:
      - RAILS_ENV=production
      - HOST_USER_ID
      - HOST_USER_GID

volumes:
  bundle:
  dbdata:
